### ISSUE TITLE
Alignment Issue

### ISSUE THREAD

**Issue by ghost** [mobyvb/midi-converter#1]
Hi Maximillian,

I found an issue with deltaTime when the first event in a track is e.g. a contoller:

[
            {
                "deltaTime": 3840,
                "channel": 1,
                "type": "channel",
                "subtype": "controller",
                "controllerType": 10,
                "value": 64,
                "realTime": 3840,
                "sortKey": 1
            },
            {
                "deltaTime": 0,
                "channel": 1,
                "type": "channel",
                "noteNumber": 33,
                "velocity": 122,
                "subtype": "noteOn",
                "realTime": 3840,
                "sortKey": 2
            },
            {
                "deltaTime": 0,
                "channel": 1,
                "type": "channel",
                "subtype": "programChange",
                "programNumber": 33,
                "realTime": 3840,
                "sortKey": 3
            },

In effect, since deltaTime for the controller is missed, the first notes will be missaligned and start playing at deltaTime 0.

Here is a quick fix, where I added a dummy noteOff operation to your jsonToMidi function - maybe you can think of some other NOP midi command that will preserve the deltaTime:

```
   else if(note.subtype === 'noteOff') {
      var noteStr = noteFromMidiPitch(note.noteNumber);
      track.addNoteOff(note.channel, noteStr, note.deltaTime);
    }
  // New Code:
else if ( note.hasOwnProperty("deltaTime") ) {
    // Dummy noteOff operation to preserve the deltaTime
    var noteStr = noteFromMidiPitch(125);
      track.addNoteOff(note.channel, noteStr, note.deltaTime);
   }
```

Best Regards
Claus Fjellø-Jensen
claus.fjello@gmail.com

**Comment by mobyvb** [comment]
This seems to be a limitation with [jsmidgen](https://github.com/dingram/jsmidgen) (the library I'm using for json -> midi conversion). I don't think it has an option to add controller event types. I think the noteOff solution you've proposed is a nice fix for now, but I'm concerned about the small chance that it turns a note off that is on when the controller event occurs. We could probably get around this by selecting a note that is never called. I think 125, which you picked is sufficient since it's in the 9th octave, though I don't know if MIDI has a min/max for notes you can pick.

Feel free to make a pull request with that change and I'll merge it in. Otherwise I can make that change myself.

**Comment by ghost** [comment]
Hi ,
Well, my quick solution was a little to quick it seems, at least for some other midi events in the files that I am manipulating, so I will have to double check before making any real changes to your code.
Br,
Claus

Sendt fra min iPad

**Comment by mobyvb** [comment]
Alright, sounds good.

Moby
